"""empty message

Revision ID: a6ce3ddca8e6
Revises: 
Create Date: 2018-11-20 20:07:40.658468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ce3ddca8e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('author_id'),
    sa.UniqueConstraint('first_name', 'last_name', 'middle_name')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('book_collection',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('collection_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('checkout',
    sa.Column('checkout_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_copy_id', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('checkout_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_first_name', sa.String(), nullable=False),
    sa.Column('user_last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_first_name', 'user_last_name', 'email')
    )
    op.create_table('authorship',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('book_copy',
    sa.Column('book_copy_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('is_checked_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.PrimaryKeyConstraint('book_copy_id')
    )
    op.create_table('collections',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['book_collection.collection_id'], ),
    sa.PrimaryKeyConstraint('book_id', 'collection_id')
    )
    op.create_table('note',
    sa.Column('note_title', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], ),
    sa.PrimaryKeyConstraint('note_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('collections')
    op.drop_table('book_copy')
    op.drop_table('authorship')
    op.drop_table('user')
    op.drop_table('checkout')
    op.drop_table('book_collection')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
